import * as os from 'os';
import { convertQuizToLaTeX } from '../src/convertQuizToLaTeX'
import { parse, GIFTQuestion } from 'gift-pegjs';

describe('conversion', () => {
    const giftString = [
        'What is 2 + 2 {=4 ~3 ~5}',
        '',
        'Question {',
        '    =Correct Answer',
        '    ~Incorrect Answer 1',
        '    ~Incorrect Answer 2',
        '    ~Incorrect Answer 3',
        '}'].join(os.EOL)

    const quiz = parse(giftString)

    it('should convert 2-question GIFT to LaTeX', () => {
        expect(convertQuizToLaTeX(quiz, "1", false, false)).toEqual(
            ['% LaTeX generated by gift2latex (npm package)',
                '\\begin{questions}',
                '\\question[1]',
                'What is 2 + 2',
                '\\begin{choices}',
                '\\CorrectChoice 4',
                '\\choice 3',
                '\\choice 5',
                '\\end{choices}',
                '\\question[1]',
                'Question',
                '\\begin{choices}',
                '\\CorrectChoice Correct Answer',
                '\\choice Incorrect Answer 1',
                '\\choice Incorrect Answer 2',
                '\\choice Incorrect Answer 3',
                '\\end{choices}',
                '\\end{questions}'].join(os.EOL));
    });

    it('should convert 2-question GIFT to LyX', () => {
        expect(convertQuizToLaTeX(quiz, "1", false, true)).toEqual(
            ['% LaTeX generated by gift2latex (npm package)',
                '\\begin{myquestions}',
                '\\myquestion[1]',
                'What is 2 + 2',
                '\\begin{choices}',
                '\\CorrectChoice 4',
                '\\choice 3',
                '\\choice 5',
                '\\end{choices}',
                '\\myquestion[1]',
                'Question',
                '\\begin{choices}',
                '\\CorrectChoice Correct Answer',
                '\\choice Incorrect Answer 1',
                '\\choice Incorrect Answer 2',
                '\\choice Incorrect Answer 3',
                '\\end{choices}',
                '\\end{myquestions}'].join(os.EOL));
    });

    it('should convert 2-question GIFT to LaTeX with \\half points', () => {
        expect(convertQuizToLaTeX(quiz, "\\half", false, false)).toEqual(
            ['% LaTeX generated by gift2latex (npm package)',
                '\\begin{questions}',
                '\\question[\\half]',
                'What is 2 + 2',
                '\\begin{choices}',
                '\\CorrectChoice 4',
                '\\choice 3',
                '\\choice 5',
                '\\end{choices}',
                '\\question[\\half]',
                'Question',
                '\\begin{choices}',
                '\\CorrectChoice Correct Answer',
                '\\choice Incorrect Answer 1',
                '\\choice Incorrect Answer 2',
                '\\choice Incorrect Answer 3',
                '\\end{choices}',
                '\\end{questions}'].join(os.EOL));
    });

});