import { parse, GIFTQuestion, QuestionType } from "gift-pegjs";
import yargs, {Argv} from "yargs";
import {readFileSync} from 'fs';

const argv = yargs
    .alias('i', 'input')
    .alias('s', 'shuffle')
    .demandOption('input').argv;

const questions = readFileSync(argv.input as string,'utf8');

const quiz: GIFTQuestion[] = parse(questions)

console.log("% LaTeX generated by gift2latex (npm package)")
console.log("\\begin{questions}")

for (let question of quiz) {
    switch(question.type) {
        case "MC":
        console.log("\\question")
        console.log(question.stem.text)
        console.log("\\begin{choices}")
        // https://stackoverflow.com/a/46545530/1168342
        let choices = argv.shuffle ? question.choices.map((a) => ({sort: Math.random(), value: a}))
            .sort((a, b) => a.sort - b.sort)
            .map((a) => a.value) : question.choices;
        for (let choice of choices) {
            console.log("\\" + (choice.isCorrect ? "CorrectChoice " : "choice ") + choice.text.text)
        }
        console.log("\\end{choices}")

    }
}

console.log("\\end{questions}")
